START-OF-LOG: 3.0
CONTEST: ARRL-SS-SSB
CALLSIGN: [% mycall %]
LOCATION: [% mysection %]
[% SWITCH myprec -%]
[%  CASE "A" -%]
CATEGORY-OPERATOR: SINGLE-OP
CATEGORY-TRANSMITTER: ONE
CATEGORY-ASSISTED: NON-ASSISTED
CATEGORY-BAND: ALL
CATEGORY-POWER: LOW
CATEGORY-MODE: SSB
CATEGORY-STATION: FIXED
[%  CASE "B" -%]
CATEGORY-OPERATOR: SINGLE-OP
CATEGORY-TRANSMITTER: ONE
CATEGORY-ASSISTED: NON-ASSISTED
CATEGORY-BAND: ALL
CATEGORY-POWER: HIGH
CATEGORY-MODE: SSB
CATEGORY-STATION: FIXED
[%  CASE "M" -%]
CATEGORY-OPERATOR: MULTI-OP
CATEGORY-TRANSMITTER: ONE
CATEGORY-ASSISTED: ASSISTED
CATEGORY-BAND: ALL
CATEGORY-POWER: HIGH
CATEGORY-MODE: SSB
CATEGORY-STATION: FIXED
[%  CASE "Q" -%]
CATEGORY-OPERATOR: SINGLE-OP
CATEGORY-TRANSMITTER: ONE
CATEGORY-ASSISTED: NON-ASSISTED
CATEGORY-BAND: ALL
CATEGORY-POWER: QRP
CATEGORY-MODE: SSB
CATEGORY-STATION: FIXED
[%  CASE "U" -%]
CATEGORY-OPERATOR: SINGLE-OP
CATEGORY-TRANSMITTER: ONE
CATEGORY-ASSISTED: ASSISTED
CATEGORY-BAND: ALL
CATEGORY-POWER: HIGH
CATEGORY-MODE: SSB
CATEGORY-STATION: FIXED
[% END -%]
CLUB: [% myclub %]
CLAIMED-SCORE: 13224
CONTEST: ARRL-SS-SSB
CREATED-BY: vrpsweeps.pl
NAME: [% myname %]
ADDRESS: [% myaddress1 %]
ADDRESS: [% myaddress2 %]
OPERATORS: [% myoperators %]
