START-OF-LOG: 3.0
CONTEST: ARRL-SS-SSB
CALLSIGN: [% call %]
LOCATION: [% section %]
[% SWITCH precedence.upper -%]
[%  CASE "A" -%]
CATEGORY-OPERATOR: SINGLE-OP
CATEGORY-TRANSMITTER: ONE
CATEGORY-ASSISTED: NON-ASSISTED
CATEGORY-BAND: ALL
CATEGORY-POWER: LOW
CATEGORY-MODE: SSB
CATEGORY-STATION: FIXED
[%  CASE "B" -%]
CATEGORY-OPERATOR: SINGLE-OP
CATEGORY-TRANSMITTER: ONE
CATEGORY-ASSISTED: NON-ASSISTED
CATEGORY-BAND: ALL
CATEGORY-POWER: HIGH
CATEGORY-MODE: SSB
CATEGORY-STATION: FIXED
[%  CASE "M" -%]
CATEGORY-OPERATOR: MULTI-OP
CATEGORY-TRANSMITTER: ONE
CATEGORY-ASSISTED: ASSISTED
CATEGORY-BAND: ALL
CATEGORY-POWER: HIGH
CATEGORY-MODE: SSB
CATEGORY-STATION: FIXED
[%  CASE "Q" -%]
CATEGORY-OPERATOR: SINGLE-OP
CATEGORY-TRANSMITTER: ONE
CATEGORY-ASSISTED: NON-ASSISTED
CATEGORY-BAND: ALL
CATEGORY-POWER: QRP
CATEGORY-MODE: SSB
CATEGORY-STATION: FIXED
[%  CASE "U" -%]
CATEGORY-OPERATOR: SINGLE-OP
CATEGORY-TRANSMITTER: ONE
CATEGORY-ASSISTED: ASSISTED
CATEGORY-BAND: ALL
CATEGORY-POWER: HIGH
CATEGORY-MODE: SSB
CATEGORY-STATION: FIXED
[% END -%]
CLUB: [% club %]
CLAIMED-SCORE: 13224
CONTEST: ARRL-SS-SSB
CREATED-BY: vrpsweeps.pl
NAME: [% name %]
ADDRESS: [% address1 %]
ADDRESS: [% address2 %]
OPERATORS: [% operators %]
